# Generated by Django 2.2.24 on 2021-08-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True)),
                ('phoneNumber', models.PositiveIntegerField(blank=True)),
                ('priceEstimated', models.PositiveIntegerField(blank=True)),
                ('timeEstimated', models.PositiveIntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
